### ISSUE TITLE
rprompt::prompt_reply_stdout() returns string with \r on Windows

### ISSUE THREAD

**Issue by anjumkaiser** [conradkdotcom/rprompt#1]
I am using rprompt::prompt_reply_stdout() and it is returning the string with trailing \r character on windows.
Works fine on Linux, but on windows it does not remove trailing \r character.
This affects rpassword too, where same behavior is present in rprompt::prompt_reply_stdout()

**Comment by conradkdotcom** [comment]
Sounds like a bug in the Rust standard library. But it is fixable. I will push a fix tonight. Do you mind if I ping you then so you can try again please ? 😃

**Comment by conradkleinespel** [comment]
Should be fixed now:
https://github.com/conradkdotcom/rprompt/commit/041fcb6f923b32b227a97064704dec6b8a5d1da5
https://github.com/conradkdotcom/rpassword/commit/bdb23afac55472acd8095d69daa367f3f6fe5338

**Comment by conradkleinespel** [comment]
Can you please let me know if these fixes work for you ? @anjumkaiser

**Comment by anjumkaiser** [comment]
confirmed, it is now fixed.

**Comment by conradkleinespel** [comment]
@anjumkaiser great !

**Comment by conradkleinespel** [comment]
@anjumkaiser thanks a lot for reporting this and for your feedback !
