### ISSUE TITLE
Integrate ctrlc support.

### ISSUE THREAD

**Issue by crlf0710** [conradkdotcom/rprompt#2]
Hi, i'm trying to implement something like node.js repl. in which you can ctrl-c to abandon current line input, and double ctrl-c on a blank line to quit.  However `prompt_reply_stderr()` doesn't give the buffer back when ctrl-c is pressed, making this impossible.

**Comment by conradkleinespel** [comment]
@crlf0710 Hi ! Good point ! I'm glad to accept a PR with a new function that allows CTRL-C support. I'm saying a *new* function so that backwards compatibility is preserved.

**Comment by crlf0710** [comment]
Currently i'm using another crate for this now. I'm gonna close this.
